name: oaas

services:
  #env_file 옵션
  api:
    build: .
    container_name: back_dev
    env_file:
      - .env # ← Docker가 직접 주입
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - oaas-net
  # db / portgresql
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin01
      POSTGRES_PASSWORD: admin01
      POSTGRES_DB: OAAS_DB
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oaas-net
  # redis:
  #   image: redis:7-alpine
  #   container_name: asdf_redis
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data: {}

networks:
  oaas-net:
    external: true
